// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Fri Nov 09 05:54:23 2018

addsub_32 addsub_32_inst
(
	.add_sub(add_sub_sig) ,	// input  add_sub_sig
	.dataa(dataa_sig) ,	// input [31:0] dataa_sig
	.datab(datab_sig) ,	// input [31:0] datab_sig
	.cout(cout_sig) ,	// output  cout_sig
	.result(result_sig) 	// output [31:0] result_sig
);

