// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Wed Oct 24 22:58:02 2018

jt51 jt51_inst
(
	.clk(clk) ,	// input  clk
	.rst(rst) ,	// input  rst
	.cs_n(cs_n) ,	// input  cs_n
	.wr_n(wr_n) ,	// input  wr_n
	.a0(a0) ,	// input  a0
	.d_in(d_in) ,	// input [7:0] d_in
	.d_out(d_out) ,	// output [7:0] d_out
	.ct1(ct1) ,	// output  ct1
	.ct2(ct2) ,	// output  ct2
	.irq_n(irq_n) ,	// output  irq_n
	.p1(p1) ,	// output  p1
	.sample(sample) ,	// output  sample
	.left(left) ,	// output [15:0] left
	.right(right) ,	// output [15:0] right
	.xleft(xleft) ,	// output [15:0] xleft
	.xright(xright) ,	// output [15:0] xright
	.dacleft(dacleft) ,	// output [15:0] dacleft
	.dacright(dacright) 	// output [15:0] dacright
);

