// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Fri Nov 09 05:54:23 2018

loop loop_inst
(
	.rst(rst_sig) ,	// input  rst_sig
	.clk(clk_sig) ,	// input  clk_sig
	.inst_in(inst_in_sig) ,	// input [19:0] inst_in_sig
	.i_fetch(i_fetch_sig) ,	// input  i_fetch_sig
	.a_src(a_src_sig) ,	// input [5:0] a_src_sig
	.pc_in(pc_in_sig) ,	// input [10:0] pc_in_sig
	.pc_out(pc_out_sig) ,	// output [10:0] pc_out_sig
	.branch(branch_sig) ,	// output  branch_sig
	.skip(skip_sig) ,	// output  skip_sig
	.lcount(lcount_sig) 	// output [3:0] lcount_sig
);

