// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Fri Nov 09 05:54:23 2018

test test_inst
(
	.rst(rst_sig) ,	// input  rst_sig
	.clk(clk_sig) ,	// input  clk_sig
	.inst_in(inst_in_sig) ,	// input [19:0] inst_in_sig
	.flg_in(flg_in_sig) ,	// input [3:0] flg_in_sig
	.sr_in(sr_in_sig) ,	// input [15:0] sr_in_sig
	.a_src(a_src_sig) ,	// input [15:0] a_src_sig
	.ea1b(ea1b_sig) ,	// input [15:0] ea1b_sig
	.extw(extw_sig) ,	// input [15:0] extw_sig
	.branch(branch_sig) 	// output  branch_sig
);

